import { Mission, MissionPhase } from '../types';

export const missions: Mission[] = [
  {
    id: 'training-1',
    name: 'Basic Flight Training',
    description: 'Learn the fundamentals of rocket control and launch procedures.',
    objectives: [
      {
        id: 'obj-1',
        description: 'Start engines',
        completed: false,
        optional: false,
        progress: 0,
        targetValue: 1,
      },
      {
        id: 'obj-2',
        description: 'Reach 1000m altitude',
        completed: false,
        optional: false,
        progress: 0,
        targetValue: 1000,
      },
      {
        id: 'obj-3',
        description: 'Land safely',
        completed: false,
        optional: false,
        progress: 0,
        targetValue: 1,
      },
    ],
    phases: [MissionPhase.PRE_FLIGHT, MissionPhase.LAUNCH, MissionPhase.LANDING],
    duration: 300,
    difficulty: 'easy',
    rewards: {
      experience: 100,
      credits: 500,
    },
    prerequisites: [],
  },
  {
    id: 'suborbital-1',
    name: 'Suborbital Flight',
    description: 'Reach the edge of space and return safely.',
    objectives: [
      {
        id: 'obj-1',
        description: 'Reach Karman line (100km)',
        completed: false,
        optional: false,
        progress: 0,
        targetValue: 100000,
      },
      {
        id: 'obj-2',
        description: 'Achieve 2500 m/s velocity',
        completed: false,
        optional: false,
        progress: 0,
        targetValue: 2500,
      },
      {
        id: 'obj-3',
        description: 'Safe re-entry',
        completed: false,
        optional: false,
        progress: 0,
        targetValue: 1,
      },
      {
        id: 'obj-4',
        description: 'Precision landing (within 1km)',
        completed: false,
        optional: true,
        progress: 0,
        targetValue: 1000,
      },
    ],
    phases: [
      MissionPhase.PRE_FLIGHT,
      MissionPhase.LAUNCH,
      MissionPhase.ASCENT,
      MissionPhase.RE_ENTRY,
      MissionPhase.LANDING,
    ],
    duration: 900,
    difficulty: 'easy',
    rewards: {
      experience: 300,
      credits: 1500,
    },
    prerequisites: ['training-1'],
  },
  {
    id: 'orbital-1',
    name: 'Orbital Insertion',
    description: 'Achieve stable low Earth orbit.',
    objectives: [
      {
        id: 'obj-1',
        description: 'Reach 200km altitude',
        completed: false,
        optional: false,
        progress: 0,
        targetValue: 200000,
      },
      {
        id: 'obj-2',
        description: 'Achieve orbital velocity (7800 m/s)',
        completed: false,
        optional: false,
        progress: 0,
        targetValue: 7800,
      },
      {
        id: 'obj-3',
        description: 'Maintain orbit for 1 orbit',
        completed: false,
        optional: false,
        progress: 0,
        targetValue: 90,
      },
      {
        id: 'obj-4',
        description: 'De-orbit burn',
        completed: false,
        optional: false,
        progress: 0,
        targetValue: 1,
      },
      {
        id: 'obj-5',
        description: 'Safe landing',
        completed: false,
        optional: false,
        progress: 0,
        targetValue: 1,
      },
    ],
    phases: [
      MissionPhase.PRE_FLIGHT,
      MissionPhase.LAUNCH,
      MissionPhase.ASCENT,
      MissionPhase.ORBIT_INSERTION,
      MissionPhase.ORBIT,
      MissionPhase.RE_ENTRY,
      MissionPhase.LANDING,
    ],
    duration: 5400,
    difficulty: 'medium',
    rewards: {
      experience: 800,
      credits: 4000,
    },
    prerequisites: ['suborbital-1'],
  },
  {
    id: 'docking-1',
    name: 'Docking Operations',
    description: 'Dock with the International Space Station.',
    objectives: [
      {
        id: 'obj-1',
        description: 'Reach orbit',
        completed: false,
        optional: false,
        progress: 0,
        targetValue: 1,
      },
      {
        id: 'obj-2',
        description: 'Match ISS orbit',
        completed: false,
        optional: false,
        progress: 0,
        targetValue: 1,
      },
      {
        id: 'obj-3',
        description: 'Approach within 100m',
        completed: false,
        optional: false,
        progress: 0,
        targetValue: 100,
      },
      {
        id: 'obj-4',
        description: 'Successful docking',
        completed: false,
        optional: false,
        progress: 0,
        targetValue: 1,
      },
      {
        id: 'obj-5',
        description: 'Return to Earth',
        completed: false,
        optional: false,
        progress: 0,
        targetValue: 1,
      },
    ],
    phases: [
      MissionPhase.PRE_FLIGHT,
      MissionPhase.LAUNCH,
      MissionPhase.ASCENT,
      MissionPhase.ORBIT_INSERTION,
      MissionPhase.ORBIT,
      MissionPhase.DOCKING,
      MissionPhase.RE_ENTRY,
      MissionPhase.LANDING,
    ],
    duration: 7200,
    difficulty: 'hard',
    rewards: {
      experience: 2000,
      credits: 10000,
    },
    prerequisites: ['orbital-1'],
  },
  {
    id: 'moon-1',
    name: 'Lunar Approach',
    description: 'Journey to the Moon and establish lunar orbit.',
    objectives: [
      {
        id: 'obj-1',
        description: 'Earth orbit',
        completed: false,
        optional: false,
        progress: 0,
        targetValue: 1,
      },
      {
        id: 'obj-2',
        description: 'Trans-lunar injection',
        completed: false,
        optional: false,
        progress: 0,
        targetValue: 1,
      },
      {
        id: 'obj-3',
        description: 'Lunar orbit insertion',
        completed: false,
        optional: false,
        progress: 0,
        targetValue: 1,
      },
      {
        id: 'obj-4',
        description: 'Lunar landing',
        completed: false,
        optional: false,
        progress: 0,
        targetValue: 1,
      },
      {
        id: 'obj-5',
        description: 'Return to Earth',
        completed: false,
        optional: false,
        progress: 0,
        targetValue: 1,
      },
    ],
    phases: [
      MissionPhase.PRE_FLIGHT,
      MissionPhase.LAUNCH,
      MissionPhase.ASCENT,
      MissionPhase.ORBIT_INSERTION,
      MissionPhase.ORBIT,
      MissionPhase.RE_ENTRY,
      MissionPhase.LANDING,
    ],
    duration: 86400,
    difficulty: 'extreme',
    rewards: {
      experience: 10000,
      credits: 50000,
    },
    prerequisites: ['docking-1'],
  },
];

export const getAvailableMissions = (completedMissions: string[]): Mission[] => {
  return missions.filter((mission) => {
    if (completedMissions.includes(mission.id)) return false;
    const hasPrerequisites = mission.prerequisites.every((prereq) =>
      completedMissions.includes(prereq)
    );
    return hasPrerequisites;
  });
};
